model:
  name: "SegmentationModel"
  num_classes: 3
  input_size: [256, 256]


  pretrained: true

dataset:
  path: "data/images"
  batch_size: 16
  shuffle: true
  num_workers: 4

training:
  epochs: 50
  learning_rate: 0.001
  weight_decay: 0.0001
  save_model: true
  save_path: "models/segmentation_model.pth"

evaluation:
  metrics: ["accuracy", "iou"]
  validation_split: 0.2