model:
  name: "UNet"
  input_size: [256, 256]
  num_classes: 3

training:
  batch_size: 16
  learning_rate: 0.001
  num_epochs: 50
  validation_split: 0.2

data:
  dataset_path: "/path/to/dataset"
  image_size: [256, 256]
  augmentations:
    - "horizontal_flip"
    - "vertical_flip"
    - "rotation"

output:
  model_save_path: "./models/unet_model.h5"
  predictions_save_path: "./predictions/"